#!/bin/bash

# Exit and block git push if there's any error
set -e

# Commands
npm install
npm run build

echo "Running formatter..."
npm run format

echo "Staging formatted files..."
git add -u

echo "Running linter..."
npm run lint

echo "Running tests..."
npm run test
npm run preview
npm run test:e2e

echo "All checks passed. Proceeding with push."
