#!/bin/bash

# Exit and block git push if there's any error
set -e

# Commands
npm install

echo "Running linter... (Please run `npm run format` before pushing)"
npm run lint

echo "Running tests..."
npm run test

echo "All checks passed. Proceeding with push."
